name: Unit Tests

on:
  push:
    branches:
    - 'master'
    - 'main'
  pull_request:
    branches:
    - 'master'
    - 'main'

jobs:
  testing:
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
        environment: [ test ]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup pixi
      uses: prefix-dev/setup-pixi@v0.8.1
      with:
        pixi-version: v0.29.0
        environments: ${{ matrix.environment }}
        frozen: true

    - name: Run tests
      run: pixi run -e ${{ matrix.environment }} test

#    - name: Upload coverage reports to Codecov
#      uses: codecov/codecov-action@v4.5.0
#      with:
#        token: ${{ secrets.CODECOV_TOKEN }}
#        slug: scikit-learn-contrib/project-template
